---
title: "Un joli titre pour le dashboard"
author: "Marie-Pierre Etienne"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    orientation: columns
    vertical_layout: fill
    navbar:
      - { title: "Moodle", href: "https://tice.agrocampus-ouest.fr/course/view.php?id=6726", align: left }
      - { icon: "fa-twitter", href: "https://twitter.com/marie_etienne", align: right }
      - { icon: "fa-linkedin", href: "https://www.linkedin.com/in/marie-etienne-818a7115/", align: right }
params:
  setup_path: ../resources/
---

<style>                     
.navbar {
  background-color:#46ACC8;
  border-color:#46ACC8;
}
.navbar-brand {
color:black!important;
}

</style>   


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(plotly)
library(sf)
library(maps)
library(dplyr)
library(highcharter) 
```

Importation des données et chargement des packages

```{r data}
religion_brut <- read.csv("WRP national data.csv")
alcool_brut <- read.csv("HappinessAlcoholConsumption.csv")
alcool_religion <- countrycode::codelist %>% 
  select(country.name.en, cowc) %>% 
  rename(Country = country.name.en) %>% 
  right_join(alcool_brut, by = "Country") %>% 
  rename(name = cowc) %>% 
  full_join(religion_brut, by = "name") 
```

### Graphiques A : Religions et consommation d'alcool à travers le monde

```{r}
world_sf <- map_data("world")

religion_main <- religion_brut %>% 
  filter(year==2010) %>% 
  select(name, ends_with("pct"), nonreligpct, -ends_with("genpct"), -sumreligpct,
         hindgenpct, sikhgenpct, shntgenpct, zorogenpct, bahgenpct,
         taogenpct, confgenpct, anmgenpct) %>% 
  pivot_longer(cols = c(ends_with("pct"), nonreligpct), 
               names_to = "religion", values_to = "percent") %>% 
  group_by(name) %>% 
  filter(percent==max(percent)) %>% 
  mutate(religion = as.factor(religion)) %>% 
  mutate(religion = fct_recode(religion,
                               'buddistes' = "budmahpct",
                               'buddistes' = "budothrpct",
                               'buddistes' = "budthrpct",
                               'chrétiens - protestants' = "chrstangpct",
                               'chrétiens - catholiques' = "chrstcatpct",
                               'chrétiens - orthodoxes' = "chrstorthpct",
                               'chrétiens - protestants' = "chrstprotpct",
                               'chrétiens - autres' = "chrstothrpct",
                               'musulmans - sunnites' = "islmsunpct",
                               'musulmans - shiites' = "islmshipct",
                               'musulmans - autres' = "islmothrpct",
                               'juifs orthodoxes' = "judorthpct",
                               'athées' = "nonreligpct",
                               'animistes' = "anmgenpct",
                               'hindous' = "hindgenpct",
                               'shintoistes' = "shntgenpct"
                               ))

palette_religion = c(
  `chrétiens - catholiques` = "#00b4ff",
  `chrétiens - orthodoxes` = "#009eff",
  `chrétiens - protestants` = "#0066ff",
  `chrétiens - autres` = "#004fff",
  `musulmans - sunnites` = "#4d7f17",
  `musulmans - shiites` = "#6bb120",
  `musulmans - autres` = "#8ae429",
  `juifs orthodoxes` = "#ea8611",
  `buddistes` = "#ffd966",
  `athées` = "#cc0000",
  `animistes` = "#7e0f12",
  `hindous` = "#6a329f",
  `shintoistes` = "#c90076"
)

religion_map <- religion_main %>%
  rename(cowc = name) %>% 
  full_join(countrycode::codelist, by = "cowc") %>% 
  select(country.name.en, religion, percent, cowc) %>% 
  rename(region = country.name.en) %>% 
  mutate(region = as.factor(region)) %>% 
  mutate(region = fct_recode(region,
                             "USA" = "United States",
                             "UK" = "United Kingdom",
                             "Antigua" = "Antigua & Barbuda",
                            "Bosnia and Herzegovina"  = "Bosnia & Herzegovina",
                            "Republic of Congo" = "Congo - Brazzaville",
                            "Democratic Republic of the Congo" = "Congo - Kinshasa",
                            "Ivory Coast" = "Côte d’Ivoire",
                            "Czech Republic" = "Czechia",
                            "Myanmar" = "Myanmar (Burma)"
                             )) %>% 
  full_join(world_sf, by = 'region') %>% 
  ggplot() +
  aes(fill = religion, x = long, y = lat, group = group,
      text = paste(round(percent, 2)*100, '%')) +
  geom_polygon() +
  coord_map("mercator", xlim = c(-180,180), ylim = c(-55, 80)) +
  scale_fill_manual(values = palette_religion) +
  xlab('') + ylab('') +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank()) +
  ggtitle("Religions majoritaires dans le monde") 

ggplotly(religion_map)

alcool_brut %>% 
  mutate(total_alcool = (Beer_PerCapita + Wine_PerCapita + Spirit_PerCapita)/100) %>% 
  select(Country, total_alcool) %>% 
  rename(region = Country) %>% 
  mutate(region = fct_recode(region,
                            'USA' = "United States",
                           'UK' = "United Kingdom",
                           'Trinidad' = "Trinidad and Tobago",
                           'Russia' = "Russian Federation",
                           'North Macedonia' = "Macedonia",
                           "Democratic Republic of the Congo" = "Dem. Rep. Congo",
                           'Republic of Congo' = "Rep. Congo",
                           'Ivory Coast' = "Cote d'Ivoire")) %>% 
  full_join(world_sf, by = "region") %>% 
  ggplot() +
  geom_polygon(aes(fill = total_alcool, x = long, y = lat, group = group)) +
  coord_map("mercator", xlim = c(-180,180), ylim = c(-55, 80)) +
  viridis::scale_fill_viridis(option = 'H', begin = 0.4)
  

library(plotly)
```


### Graphique B

Graphique de la consommation de Bière, Vin et Spiritueux en fonction de la religion (majoritaire dans chaque pays)

```{r}
data <- alcool_religion
religion_main <- data %>% 
  select(Country,ends_with("PerCapita"), ends_with("_percent")) %>% 
  select(-total_percent) %>% 
  pivot_longer(cols = ends_with("_percent"), names_to = "religion", values_to = "percent") %>% 
  group_by(Country) %>% 
  filter(percent==max(percent)) %>% 
  separate(religion, c("main", 'suffix'), sep = '_') %>% 
  select(-suffix) %>% 
  group_by(main) %>% 
  mutate(n = n()) %>% 
  filter(n>1) %>% 
  select(-n) %>% 
  mutate(main = as.factor(main)) %>%
  pivot_longer(cols = 3:5, names_to = "Type" ) %>%
  mutate(Type = as.factor(Type)) 

graph2 <- ggplot(data = religion_main)+
  aes(x=main, y=value, fill = Type)+
  geom_boxplot(outlier.shape=NA)+
  scale_fill_manual(values=c("darkgoldenrod1","aquamarine4", "darkred")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  theme(legend.position="top") + 
  scale_x_discrete(limits=c("sunni", "islam", "buddhism","christianity","noreligion"))
graph2
```

### Graphique C

```{r}
library(ggpubr)

data_graph3 <- alcool_religion %>%
  filter(year == 2010) %>% 
  select(Country,Hemisphere, ends_with ("Capita"), ends_with ("pct")) %>%
  mutate(maj_chrst = pmax(chrstprotpct,chrstcatpct, chrstorthpct, chrstothrpct)) %>% 
  mutate (courant_maj_chrst = ifelse(maj_chrst == chrstcatpct,"Catholique", ifelse(maj_chrst == chrstorthpct, "Orthodoxe", ifelse(maj_chrst== chrstothrpct, "Autres", "Protestant")) )) %>% 
  mutate(courant_maj_chrst = as.factor(courant_maj_chrst)) %>% 
  mutate(maj_islam = pmax (islmsunpct,islmshipct,islmibdpct, islmnatpct,islmalwpct,islmahmpct, islmothrpct)) %>% 
  mutate (courant_maj_islam = ifelse(maj_islam == islmsunpct,"Sunnite", ifelse(maj_islam == islmshipct, "Chiite", "Autres"))) %>% 
  mutate (courant_maj_islam = as.factor(courant_maj_islam)) %>% 
  mutate(Conso_totale = Beer_PerCapita + Wine_PerCapita + Spirit_PerCapita) %>%
  mutate (conso_max = pmax(Beer_PerCapita,Wine_PerCapita,Spirit_PerCapita)) %>% 
  filter(!is.na(Conso_totale)) %>% 
  mutate (chrstgenpct = chrstgenpct*100) %>% 
  mutate (islmgenpct = islmgenpct*100)

christ <-ggplot(data_graph3, aes(x = chrstgenpct, y = Conso_totale)) + 
  geom_point(aes(color = courant_maj_chrst), alpha = 1.2) +
  geom_smooth(method=lm, se = FALSE)+
  scale_color_manual(values = c("#00b4ff","#0066ff", "#009eff", "#004fff"), name = "Courant majoritaire", limits = c("Catholique", "Protestant", "Orthodoxe", "Autres"))+
  theme_minimal()+
  labs (x ="Proportion de chrétiens dans le pays", y ="", title = "Consommation d'alcool dans le monde", subtitle = "Zoom sur les 2 religions principales")+
  theme_classic()+
  stat_regline_equation(label.y = 550, label.x = 30, aes(label = ..rr.label..))+
  theme(plot.title = element_text(face = "bold", size = 14,hjust=0.5), plot.subtitle = element_text(size = 11,hjust=0.5))+
  theme(plot.margin = unit(c(1,1,1,1), "lines"))+
  theme(axis.text.x = element_text(angle = 30, hjust = 1,size=10),axis.line = element_line(colour = "black", size = 0.8, linetype = "solid"),axis.text.y = element_text(size=10))+
  scale_y_continuous(labels=c("0L","200L","400L","600L"))+
  scale_x_continuous(labels=c("0%","25%","50%","75%", "100%"))
christ

islam <-ggplot(data_graph3, aes(x = islmgenpct, y = Conso_totale)) + 
  geom_point(aes(color = courant_maj_islam), alpha = 1.2) +
  geom_smooth(method=lm, se = FALSE, color = "#4d7f17")+
  scale_color_manual(values = c("#4d7f17","#6bb120", "#8ae429"), name = "Courant majoritaire", limits = c("Chiite", "Sunnite", "Autres"))+
  theme_classic()+
  xlab("Proportion de musulmans dans le pays")+
  ylab("")+
  stat_regline_equation(label.y = 550, label.x = 30, aes(label = ..rr.label..))+
  theme(plot.title = element_text(face = "bold", size = 14,hjust=0.5), plot.subtitle = element_text(size = 11,hjust=0.5))+
  theme(plot.margin = unit(c(1,1,1,1), "lines"))+
  theme(axis.text.x = element_text(angle = 30, hjust = 1,size=10),axis.line = element_line(colour = "black", size = 0.8, linetype = "solid"),axis.text.y = element_text(size=10))+
  scale_y_continuous(labels=c("0L","200L","400L","600L"))+
  scale_x_continuous(labels=c("0%","25%","50%","75%", "100%"))
islam

grid.arrange(christ, islam)
```



<!-- Column {data-width=650} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ### An easy solution for dashboard -->

<!-- ```{r, echo = TRUE} -->
<!-- #install.package('flexdasboard') -->
<!-- #rmarkdown::draft("dashboard.Rmd", template = "flex_dashboard", package = "flexdashboard") -->
<!-- ``` -->

<!-- The [flexdashboard website](https://rmarkdown.rstudio.com/flexdashboard/index.html) provides multiple advanced examples. -->

<!-- ### Some static graph -->

<!-- ```{r data, eval = TRUE, echo = FALSE, results='hide', message = FALSE, warning=FALSE} -->
<!-- n <- 100 -->
<!-- dta <- tibble(size = round(rnorm(n, mean = 0, sd =10),2),  -->
<!--            color = sample(x= c('Blue', 'Yellow'), size = n, replace = TRUE)) -->

<!-- ``` -->


<!-- ```{r graph_static,  echo = FALSE,  message = FALSE, warning=FALSE} -->
<!-- p1 <- dta %>% ggplot() + -->
<!--   aes(x=color, y = size) + -->
<!--   geom_boxplot(aes(fill= color)) -->
<!-- p1 -->
<!-- ``` -->

<!-- Column {.tabset .tabset-fade} -->
<!-- ----------------------------------------------------------------------- -->


<!-- ### Some dynamic maps -->

<!-- ```{r  ggplotly, echo = TRUE,  eval = TRUE,  message = FALSE, warning=FALSE} -->
<!-- plotly::ggplotly(p1) -->
<!-- ``` -->



<!-- ### Chart C -->

<!-- ```{r} -->

<!-- ``` -->

